runtime: python311
entrypoint: gunicorn -b :$PORT app:app

# Force single instance to prevent TOCTOU issues with in-memory storage
manual_scaling:
  instances: 1

env_variables:
  FLASK_ENV: production
  FLASK_DEBUG: "false"

handlers:
  - url: /.*
    script: auto
    secure: always
